---
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:lts
  working_directory: /tmp/workspace/app/

jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: npm ci
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - app

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ./node_modules/eslint/bin/eslint.js index.js

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npx wrangler publish

workflows:
  branch:
    jobs:
      - build:
          context: cf-workers
      - test:
          context: cf-workers
          requires:
            - build

  deploy:
    jobs:
      - build:
          context: cf-workers
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - deploy:
          context: cf-workers
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
