---
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:lts

jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Lint
          command: ./node_modules/eslint/bin/eslint.js index.js

  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Publish
          command: npx wrangler publish

workflows:
  branch:
    jobs:
      - build:
          context: cf-workers

  deploy:
    jobs:
      - deploy:
          context: cf-workers
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
