---
version: 2.1

docker_auth: &docker_auth
    username: $DOCKERHUB_USERNAME
    password: $DOCKERHUB_PASSWORD

defaults: &defaults
  docker:
    - image: cimg/node:lts
      auth:
        <<: *docker_auth

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Lint
          command: ./node_modules/eslint/bin/eslint.js index.js

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Publish
          command: npx wrangler publish

workflows:
  branch:
    jobs:
      - build:
          context: cf-workers

  deploy:
    jobs:
      - deploy:
          context: cf-workers
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
